apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrentalserverdeployment
  labels:
    app: carrentalservice

spec:
  replicas: 3
  selector:
    matchLabels:
      app: carrentalservice
  template:
    metadata:
      labels:
        app: carrentalservice
    spec:
      containers:
        - name: carrentalservice
          image: carrentalserverkclusterregistry.azurecr.io/carrentalservice:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"