apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrentalserverdeployment
  labels:
    app: carrentalserver

spec:
  replicas: 3
  selector:
    matchLabels:
      app: carrentalserver
  template:
    metadata:
      labels:
        app: carrentalserver
    spec:
      containers:
        - name: carrentalserver
          image: carrentalserverkclusterregistry.azurecr.io/carrentalserver:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"