apiVersion: apps/v1
kind: Deployment
metadata:
  name: carrentalserverdeployment
  labels:
    app: carrentalserver

spec:
  replicas: 3
  selector:
    matchLabels:
      app: carrentalserver
  template:
    metadata:
      labels:
        app: carrentalserver
    spec:
      containers:
        - name: carrentalserver
          image: carrentalserverkclusterregistry.azurecr.io/carrentalserver:latest
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "5Gi"
              cpu: "1"
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_HTTP_PORTS
              value: "5000"