apiVersion: v1
kind: Service
metadata:
  name: carrentalserverservice
spec:
  type: LoadBalancer
  selector:
    app: carrentalserver
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000